name:                minerush-restapi
version:             0.1.0.0
github:              "panavtec/minerush-restapi"
license:             BSD3
author:              "Christian Panadero"
maintainer:          "panavtec@gmail.com"
copyright:           "2018 Christian Panadero"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/panavtec/minerush-restapi#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- text
- time
- wai
- warp

library:
  source-dirs: src

executables:
  minerush-restapi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minerush-restapi

tests:
  minerush-restapi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minerush-restapi
